server:
  port: 8080
  servlet:
    context-path: /api

#datasource Config
spring:
  application:
    name: user-centre
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 1234
  data:
    redis:
      port: 6379
      database: 1
      host: localhost



  session:
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
        db-config:
          logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
          logic-delete-value: 1 # 逻辑已删除值(默认为 1)
          logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




